In [1]:
import cv2
import numpy

In [2]:
img1 = cv2.imread("C:\\Users\\gajendra singh\\OneDrive\\Desktop\\picture\\bull eye 1.png")# here 1 is used for color pixels.
img1 = cv2.resize(img1, (100,200)) # width, height
print(img1)
cv2.imshow("Original Image:", img1)

cv2.waitKey(4000) # it will open our image for 4000 mili seconds
cv2.destroyAllWindows()

[[[192 190 189]
  [195 192 191]
  [197 195 194]
  ...
  [197 195 194]
  [195 192 191]
  [192 190 189]]

 [[194 192 190]
  [196 194 193]
  [199 197 195]
  ...
  [199 197 195]
  [196 194 193]
  [194 192 190]]

 [[195 192 191]
  [197 195 194]
  [199 197 196]
  ...
  [199 197 196]
  [197 195 194]
  [195 192 191]]

 ...

 [[195 192 191]
  [197 195 194]
  [199 197 196]
  ...
  [199 197 196]
  [197 195 194]
  [195 192 191]]

 [[194 192 190]
  [196 194 193]
  [199 197 195]
  ...
  [199 197 195]
  [196 194 193]
  [194 192 190]]

 [[192 190 189]
  [195 192 191]
  [197 195 194]
  ...
  [197 195 194]
  [195 192 191]
  [192 190 189]]]


In [3]:
# gray scale image
img2 = cv2.imread("C:\\Users\\gajendra singh\\OneDrive\\Desktop\\picture\\bull.png", 0)
img2 = cv2.resize(img2, (500,800)) # width, height
print(img1)
cv2.imshow("gray scale image:", img2)
print("Image in grey scale:", img2)

cv2.waitKey(4000) # it will open our image for 4000 mili seconds
cv2.destroyAllWindows()

[[[192 190 189]
  [195 192 191]
  [197 195 194]
  ...
  [197 195 194]
  [195 192 191]
  [192 190 189]]

 [[194 192 190]
  [196 194 193]
  [199 197 195]
  ...
  [199 197 195]
  [196 194 193]
  [194 192 190]]

 [[195 192 191]
  [197 195 194]
  [199 197 196]
  ...
  [199 197 196]
  [197 195 194]
  [195 192 191]]

 ...

 [[195 192 191]
  [197 195 194]
  [199 197 196]
  ...
  [199 197 196]
  [197 195 194]
  [195 192 191]]

 [[194 192 190]
  [196 194 193]
  [199 197 195]
  ...
  [199 197 195]
  [196 194 193]
  [194 192 190]]

 [[192 190 189]
  [195 192 191]
  [197 195 194]
  ...
  [197 195 194]
  [195 192 191]
  [192 190 189]]]
Image in grey scale: [[189 189 189 ... 189 189 189]
 [189 189 189 ... 189 189 189]
 [189 189 189 ... 189 189 189]
 ...
 [189 189 189 ... 189 189 189]
 [189 189 189 ... 189 189 189]
 [189 189 189 ... 189 189 189]]


In [4]:
# gray scale image
img3 = cv2.imread("C:\\Users\\gajendra singh\\OneDrive\\Desktop\\picture\\bull's.png", -1)
img3 = cv2.resize(img3, (500,800)) # width, height
cv2.imshow("new image:", img3)
print("Image in new scale:", img3)

cv2.waitKey(4000) # it will open our image for 4000 mili seconds
cv2.destroyAllWindows()

Image in new scale: [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


Enter the path and Name of an image :C:\\Users\\gajendra singh\\OneDrive\\Desktop\\picture\\bull.png
you enter this == C:\\Users\\gajendra singh\\OneDrive\\Desktop\\picture\\bull.png
